[project]
name = "vesta_si_erpnext"
version = "1.0.0"
authors = [
    { name = "Vesta Si Erpnext", email = "basawaraj@fosserp.com" }
]
description = "Payables utility for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "pandas",
    "pysftp"
]