[project]
name = "vesta_si_erpnext"
authors = [
    { name = "Vesta Si Erpnext", email = "basawaraj@fosserp.com"}
]
description = "Payables utility for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "pandas",
    "pysftp
]